// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAydm9szizbAlQZPydzUb-nqjSePhNeYhE',
    appId: '1:1009447554043:web:35d317ce5641e81a81195e',
    messagingSenderId: '1009447554043',
    projectId: 'personal-e5a80',
    authDomain: 'personal-e5a80.firebaseapp.com',
    databaseURL: 'https://personal-e5a80-default-rtdb.firebaseio.com',
    storageBucket: 'personal-e5a80.firebasestorage.app',
    measurementId: 'G-H4P0LZCSXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Heh3HbB9CeHvoNA9g6jyEr1FDhkKcyY',
    appId: '1:1009447554043:android:4367aff4e85674a481195e',
    messagingSenderId: '1009447554043',
    projectId: 'personal-e5a80',
    databaseURL: 'https://personal-e5a80-default-rtdb.firebaseio.com',
    storageBucket: 'personal-e5a80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJRRCoa2UDhtzyMIAlPoz5uqWTgOgaAYc',
    appId: '1:1009447554043:ios:032a9e3ee3995c7481195e',
    messagingSenderId: '1009447554043',
    projectId: 'personal-e5a80',
    databaseURL: 'https://personal-e5a80-default-rtdb.firebaseio.com',
    storageBucket: 'personal-e5a80.firebasestorage.app',
    iosBundleId: 'com.example.crypto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJRRCoa2UDhtzyMIAlPoz5uqWTgOgaAYc',
    appId: '1:1009447554043:ios:032a9e3ee3995c7481195e',
    messagingSenderId: '1009447554043',
    projectId: 'personal-e5a80',
    databaseURL: 'https://personal-e5a80-default-rtdb.firebaseio.com',
    storageBucket: 'personal-e5a80.firebasestorage.app',
    iosBundleId: 'com.example.crypto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAydm9szizbAlQZPydzUb-nqjSePhNeYhE',
    appId: '1:1009447554043:web:e0fb265cb7aa9f5b81195e',
    messagingSenderId: '1009447554043',
    projectId: 'personal-e5a80',
    authDomain: 'personal-e5a80.firebaseapp.com',
    databaseURL: 'https://personal-e5a80-default-rtdb.firebaseio.com',
    storageBucket: 'personal-e5a80.firebasestorage.app',
    measurementId: 'G-6T6LH10CD4',
  );
}
